name: Deploy Express App

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Zip the Project
        run: zip -r deploy.zip . -x '*.git*'

      - name: Upload to S3
        run: aws s3 cp deploy.zip s3://alexis-911/

      - name: Deploy to EC2
        run: |
          aws deploy create-deployment \
            --application-name express-app \
            --deployment-group-name express-app-group \
            --s3-location bucket=my-express-app-deploy,key=deploy.zip,bundleType=zip
